### ISSUE TITLE
Consider Gitter

### ISSUE THREAD

**Issue by dandv** [tidepool-org/tidepool-org.github.io#54]
I'm new to Tidepool and wanted to learn more about the current state of discussion from the IRC channel. Looks like there's no bot to record history though. Also, when I log back in after an absence, I will have missed the interim discussions (unless I set up a bouncer such as ZNC on a VPS, which is overkill for many users).

[Gitter](https://gitter.im/) is a modern and very popular free chat system for open-source GitHub projects, with full history tracking and search, support for Markdown, pasting images from clipboard (great for screenshots). Many JavaScript projects use it - https://gitter.im/explore/tags/javascript. It has [native Mac/Linux/Windows apps](https://gitter.im/#apps-panel) and an [IRC bridge as well](http://blog.gitter.im/long-live-irc/), so it shouldn't pose any migration problem. Gitter also integrates with Trello and Travis CI.

**Comment by jh-bate** [comment]
sounds like it could be a nice solution - thanks for the heads up, I will
have a look

**Comment by dandv** [comment]
CC @jebeck - Gitter would solve the offline pinging/monitoring problem you pointed out on #tidepool.

**Comment by jebeck** [comment]
I'm aware of that @dandv 

For me personally, the move away from an open protocol is a tough pill to swallow (correct if I'm wrong about Gitter not being open - it certainly looks proprietary), but I'm sure we'll be discussing it.

**Comment by dandv** [comment]
I'm big on open source, open data, and open protocols too. Gitter has [an IRC bridge](http://blog.gitter.im/long-live-irc/) and [open-source integrations](https://github.com/gitterHQ/services). What would be some risks of chatting over Gitter than you see, @jebeck?

**Comment by jebeck** [comment]
After looking at it a little more closely, I see that Gitter is a bit more open than I thought, especially compared to Slack, which is a place I've seen a lot of communities moving to from IRC. I'm sure we'll talk about it, as the integrations look nice.

**Comment by dandv** [comment]
Slack is indeed close. With Gitter, one can see conversations even without logging in. For example, https://gitter.im/meteor/meteor

Even more open than IRC in a sense :)

**Comment by jh-bate** [comment]
and its sooo pretty :)

**Comment by dandv** [comment]
Gitter has just announced unlimited public rooms, members per room, and chat history for open source projects - http://blog.gitter.im/2015/03/25/more-for-free/

**Comment by jebeck** [comment]
I just updated our docs - using Gitter now. So closing!
