### ISSUE TITLE
Tidepool Mobile location

### ISSUE THREAD

**Issue by clenk** [tidepool-org/tidepool-org.github.io#86]
Under "Your Applications" in https://github.com/tidepool-org/tidepool-org.github.io/blob/master/index.md#getting-started-as-a-contributor, it says that Tidepool Mobile will replace Blip Notes. It says it's under development in the Nutshell repo, but the Nutshell repo says
"[DEPRECATED] refer to https://github.com/tidepool-org/mobile-ios".

Where is development of the Android replacement happening, and could this be made more clear?

**Comment by pazaan** [comment]
Hey @clenk. Android mobile is happening at https://github.com/tidepool-org/mobile. You are right that we should update the documentation. Thanks for pointing it out!

**Comment by pazaan** [comment]
Fixed by https://github.com/tidepool-org/tidepool-org.github.io/commit/404db149936a3fa85f21547cecfc52525e5f9b2f
